version: "3"
services:

  mongo:
    image: 'mongo'
#    expose:
#      - '27017'
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db
    env_file:
      - ./.env.mongodb

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    env_file:
      - ./backend/.env
#    expose:
#      - 3000
    ports:
      - '3000:3000'
    depends_on:
      - mongo

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: always
    env_file:
      - ./frontend/.env
    ports:
      - '80:80'
    depends_on:
      - backend


volumes:
  mongo_data: